# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a26765a9d7e101deff058019c36657570144df50f84d55a63362ac1ae9e6f69d996a9690d5c4557062c302dd2e46c380607d3058100a139337291e7527a84443

test:
  secret_key_base: 55181859e08ce99d10f1a4ef27255471ddb5fc8a9343eea7c290e22c7e2ccd18e343dc7e7a18465dd89ea41114bc8bc5085f81d4fc197bf332a950f839e37178

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
